# SPDX-License-Identifier: MIT
# Copyright (c) 2022 Narf Industries LLC
# This material is based upon work supported by the Defense Advanced Research Projects Agency (DARPA) under Contract No. HR001119C0074.
names = ["NULL", "TRUE", "FALSE", "1.2", "3D", "A", "A85", "AA", "AC",
         "AESV2", "AESV3", "AHx", "AP", "AS", "ASCII85Decode",
         "ASCIIHexDecode", "AcroForm", "Action", "ActualText",
         "Adobe.PPKLite", "All", "AllOff", "AllOn", "Alpha", "Alt",
         "Alternate", "Annot", "Annots", "AnyOff", "App", "Approved",
         "ArtBox", "AsIs", "Ascent", "AuthEvent", "B", "BBox", "BC",
         "BE", "BG", "BM", "BPC", "BS", "Background", "BaseEncoding",
         "BaseFont", "BaseState", "BitsPerComponent",
         "BitsPerCoordinate", "BitsPerFlag", "BitsPerSample",
         "BlackIs1", "BlackPoint", "BleedBox", "Blinds", "Border",
         "Bounds", "Box", "Bt", "Btn", "Butt", "ByteRange", "C", "C0",
         "C1", "CA", "CCF", "CCITTFaxDecode", "CF", "CFM", "CI",
         "CIDFontType0", "CIDFontType0C", "CIDFontType2",
         "CIDSystemInfo", "CIDToGIDMap", "CMYK", "CS", "CalCMYK",
         "CalGray", "CalRGB", "CapHeight", "Caret", "Catalog", "Cert",
         "Ch", "Changes", "CharProcs", "Circle", "ClosedArrow",
         "Collection", "ColorSpace", "ColorTransform", "Colorants",
         "Colors", "Columns", "Confidential", "Configs",
         "ContactInfo", "Contents", "Coords", "Count", "Cover",
         "CreationDate", "Creator", "CropBox", "Crypt", "D", "DA",
         "DC", "DCT", "DCTDecode", "DL", "DOS", "DP", "DR", "DS",
         "DV", "DW", "DW2", "DamagedRowsBeforeError", "Data", "Date",
         "Decode", "DecodeParms", "Default", "DefaultCMYK",
         "DefaultGray", "DefaultRGB", "Departmental", "Desc",
         "DescendantFonts", "Descent", "Design", "Dest",
         "DestOutputProfile", "Dests", "DeviceCMYK", "DeviceGray",
         "DeviceN", "DeviceRGB", "Di", "Diamond", "Differences",
         "DigestLocation", "DigestMethod", "DigestValue", "Dissolve",
         "Dm", "DocMDP", "Document", "Domain", "Draft", "Dur", "E",
         "EF", "EarlyChange", "EmbeddedFile", "EmbeddedFiles",
         "Encode", "EncodedByteAlign", "Encoding", "Encrypt",
         "EncryptMetadata", "EndOfBlock", "EndOfLine", "Exclude",
         "Experimental", "Expired", "ExtGState", "Extend", "F", "FL",
         "FRM", "FS", "FT", "Fade", "Ff", "FieldMDP", "Fields",
         "FileAttachment", "Filespec", "Filter", "Final", "First",
         "FirstChar", "FirstPage", "Fit", "FitB", "FitBH", "FitBV",
         "FitH", "FitR", "FitV", "Fl", "Flags", "FlateDecode", "Fly",
         "Font", "FontBBox", "FontDescriptor", "FontFile",
         "FontFile2", "FontFile3", "FontMatrix", "FontName",
         "ForComment", "ForPublicRelease", "Form", "FormEx",
         "FormType", "FreeText", "Function", "FunctionType",
         "Functions", "G", "Gamma", "Glitter", "GoTo", "GoToR",
         "Group", "H", "Height", "Helv", "Highlight", "I", "IC",
         "ICCBased", "ID", "IM", "IRT", "Identity", "Identity-H",
         "Identity-V", "Image", "ImageMask", "Include", "Index",
         "Indexed", "Info", "Ink", "InkList", "Intent", "Interpolate",
         "IsMap", "ItalicAngle", "JBIG2Decode", "JBIG2Globals",
         "JPXDecode", "JS", "JavaScript", "K", "Kids", "L", "LC",
         "LE", "LJ", "LW", "LZ", "LZW", "LZWDecode", "Lab", "Lang",
         "Last", "LastChar", "LastPage", "Launch", "Length",
         "Length1", "Length2", "Length3", "Limits", "Line",
         "Linearized", "Link", "Location", "Lock", "Locked",
         "Luminosity", "M", "MCID", "MK", "ML", "MMType1", "Mac",
         "Mask", "Matrix", "Matte", "MaxLen", "MediaBox", "Metadata",
         "MissingWidth", "ModDate", "Movie", "Msg", "Multiply", "N",
         "Name", "Named", "Names", "NewWindow", "Next", "NextPage",
         "NonEFontNoWarn", "None", "Normal", "NotApproved",
         "NotForPublicRelease", "Nums", "O", "OC", "OCG", "OCGs",
         "OCMD", "OCProperties", "OE", "OFF", "ON", "OP", "OPM", "OS",
         "ObjStm", "Of", "Off", "Open", "OpenArrow", "OpenType",
         "Opt", "Order", "Ordering", "Outlines", "OutputIntents", "P",
         "PDF", "PS", "Page", "PageMode", "Pages", "PaintType",
         "Params", "Parent", "Pattern", "PatternType", "Perms",
         "PolyLine", "Polygon", "Popup", "PreRelease", "Predictor",
         "Prev", "PrevPage", "Preview", "Print", "PrinterMark",
         "ProcSet", "Producer", "Properties", "Prop_AuthTime",
         "Prop_AuthType", "Prop_Build", "PubSec", "Push", "Q",
         "QuadPoints", "R", "RBGroups", "RC", "RClosedArrow", "REx",
         "RGB", "RI", "RL", "ROpenArrow", "Range", "Reason", "Rect",
         "Redact", "Ref", "Reference", "Registry", "ResetForm",
         "Resources", "Root", "Rotate", "Rows", "RunLengthDecode",
         "S", "SMask", "SMaskInData", "Schema", "Screen",
         "Separation", "Shading", "ShadingType", "Si", "Sig",
         "SigFlags", "SigQ", "SigRef", "Size", "Slash", "Sold",
         "Sound", "Split", "Square", "Squiggly", "Stamp", "Standard",
         "StdCF", "StemV", "StmF", "StrF", "StrikeOut",
         "StructParent", "StructParents", "SubFilter", "Subtype",
         "Subtype2", "Supplement", "Symb", "T", "TI", "TR", "TR2",
         "TU", "Text", "TilingType", "Times", "Title", "ToUnicode",
         "TopSecret", "Trans", "TransformMethod", "TransformParams",
         "Transparency", "TrapNet", "TrimBox", "TrueType",
         "TrustedMode", "Tx", "Type", "Type0", "Type1", "Type1C",
         "Type3", "U", "UE", "UF", "URI", "URL", "Unchanged",
         "Uncover", "Underline", "Unix", "Usage", "UseBlackPtComp",
         "UseCMap", "UseOutlines", "UserUnit", "V", "V2", "VE",
         "Version", "Vertices", "VerticesPerRow", "View", "W", "W2",
         "WMode", "Watermark", "WhitePoint", "Widget", "Width",
         "Widths", "WinAnsiEncoding", "Wipe", "XFA", "XHeight", "XML",
         "XObject", "XRef", "XRefStm", "XStep", "XYZ", "YStep", "Yes",
         "ZaDb", "adbe.pkcs7.detached", "ca", "n0", "n1", "n2", "op"]
